# Generated by Django 5.1.3 on 2024-11-30 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/products/', verbose_name='Фото товара')),
            ],
            options={
                'verbose_name_plural': 'Фотографии товаров',
            },
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('surname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=11, verbose_name="Номер телефона без '+'")),
                ('description', models.TextField(verbose_name='Описание поставщика')),
            ],
            options={
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('available', models.BooleanField(default=True, verbose_name='Отображение товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('photos', models.ManyToManyField(to='main.productphotos', verbose_name='Фотографии товара')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.supplierprofile', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='PurchasedProductsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество купленного продукта')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product')),
            ],
            options={
                'verbose_name_plural': 'Купленные товары покупателя',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('password', models.CharField(max_length=55, verbose_name='Пароль')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('purchased_products', models.ManyToManyField(blank=True, to='main.purchasedproductsusers')),
            ],
            options={
                'verbose_name_plural': 'Покупатели',
            },
        ),
    ]
